In [1]:
!pip install requests

Requirement already satisfied: requests in c:\users\arund\anaconda3\lib\site-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\arund\anaconda3\lib\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\arund\anaconda3\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\arund\anaconda3\lib\site-packages (from requests) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\arund\anaconda3\lib\site-packages (from requests) (2025.10.5)

In [3]:
import pandas as pd

market_df = pd.read_csv("Dataset2_Market_Locations.csv")

market_df.head()

     state            district               market   latitude  longitude
0   Odisha           Sambalpur        Sahaspur APMC  21.341608  83.958399
1   Odisha         Mayurbhanja        Baripada APMC  21.954103  86.742898
2  Keralam  Kozhikode(Calicut)        Mukkom Market  11.248020  75.780400
3  Keralam             Wayanad  Mananthavady Market  11.678470  75.975073
4  Gujarat              Rajkot          Jasdan APMC  22.037500  71.206497

In [5]:
import pandas as pd
import requests
import time

weather_data = []

total = len(market_df)

print(f"Total Markets : {total}")

for i, row in market_df.iterrows():

    if pd.isna(row["latitude"]) or pd.isna(row["longitude"]):
        continue

    url = (
        f"https://archive-api.open-meteo.com/v1/archive?"
        f"latitude={row['latitude']}"
        f"&longitude={row['longitude']}"
        f"&start_date=2026-07-13"
        f"&end_date=2026-07-13"
        f"&daily=temperature_2m_mean,"
        f"relative_humidity_2m_mean,"
        f"precipitation_sum,"
        f"wind_speed_10m_max,"
        f"weather_code"
        f"&timezone=auto"
    )

    try:

        response = requests.get(url, timeout=30)

        data = response.json()

        daily = data["daily"]

        weather_data.append({
            "market": row["market"],
            "latitude": row["latitude"],
            "longitude": row["longitude"],
            "temperature": daily["temperature_2m_mean"][0],
            "humidity": daily["relative_humidity_2m_mean"][0],
            "rainfall": daily["precipitation_sum"][0],
            "wind_speed": daily["wind_speed_10m_max"][0],
            "weather_code": daily["weather_code"][0]
        })

    except Exception as e:

        print(f"Error : {row['market']}")

    if (i + 1) % 20 == 0:

        pd.DataFrame(weather_data).to_csv(
            "checkpoint_weather.csv",
            index=False
        )

        print(f"{i+1}/{total} completed")

    time.sleep(0.5)

weather_df = pd.DataFrame(weather_data)

weather_df.to_csv(
    "Dataset3_Weather.csv",
    index=False
)

print("\nWeather Dataset Created Successfully!")

print(weather_df.shape)

display(weather_df.head())

Total Markets : 1391
20/1391 completed
40/1391 completed
60/1391 completed
Error : Karimangalam(Uzhavar Sandhai)
80/1391 completed
100/1391 completed
120/1391 completed
140/1391 completed
160/1391 completed
180/1391 completed
200/1391 completed
220/1391 completed
240/1391 completed
260/1391 completed
280/1391 completed
300/1391 completed
320/1391 completed
340/1391 completed
360/1391 completed
380/1391 completed
400/1391 completed
420/1391 completed
440/1391 completed
460/1391 completed
480/1391 completed
500/1391 completed
520/1391 completed
540/1391 completed
560/1391 completed
580/1391 completed
600/1391 completed
620/1391 completed
Error : Rajgarh APMC
640/1391 completed
660/1391 completed
680/1391 completed
700/1391 completed
720/1391 completed
740/1391 completed
760/1391 completed
780/1391 completed
800/1391 completed
820/1391 completed
840/1391 completed
860/1391 completed
880/1391 completed
900/1391 completed
920/1391 completed
940/1391 completed
960/1391 completed
980/1391 completed
1000/1391 completed
1020/1391 completed
1040/1391 completed
1060/1391 completed
1080/1391 completed
1100/1391 completed
1120/1391 completed
1140/1391 completed
1160/1391 completed
1180/1391 completed
1200/1391 completed
1220/1391 completed
Error : Thiruppur APMC
1240/1391 completed
1260/1391 completed
1280/1391 completed
1300/1391 completed
1320/1391 completed
1340/1391 completed
1360/1391 completed
1380/1391 completed

Weather Dataset Created Successfully!
(1388, 8)

,market,latitude,longitude,temperature,humidity,rainfall,wind_speed,weather_code
0,Sahaspur APMC,21.341608,83.958399,30.7,67,0.8,17.3,51
1,Baripada APMC,21.954103,86.742898,29.4,85,3.6,15.7,55
2,Mukkom Market,11.248020,75.780400,27.1,86,2.7,22.9,51
3,Mananthavady Market,11.678470,75.975073,23.2,91,3.3,11.5,51
4,Jasdan APMC,22.037500,71.206497,29.0,72,0.0,30.9,3

In [6]:
import pandas as pd

weather_df = pd.read_csv("Dataset3_Weather.csv")

In [7]:
weather_df.shape

(1388, 8)

In [8]:
print(weather_df.isnull().sum())

market          0
latitude        0
longitude       0
temperature     0
humidity        0
rainfall        0
wind_speed      0
weather_code    0
dtype: int64

In [9]:
print("Duplicate Rows :", weather_df.duplicated().sum())

Duplicate Rows : 0

In [10]:
print("Duplicate Markets :", weather_df["market"].duplicated().sum())

Duplicate Markets : 10

In [11]:
invalid_temp = weather_df[
    (weather_df["temperature"] < -10) |
    (weather_df["temperature"] > 60)
]

print(invalid_temp.shape)

(0, 8)

In [12]:
invalid_humidity = weather_df[
    (weather_df["humidity"] < 0) |
    (weather_df["humidity"] > 100)
]

print(invalid_humidity.shape)

(0, 8)

In [13]:
invalid_rain = weather_df[
    weather_df["rainfall"] < 0
]

print(invalid_rain.shape)

(0, 8)

In [14]:
invalid_wind = weather_df[
    weather_df["wind_speed"] < 0
]

print(invalid_wind.shape)

(0, 8)

In [15]:
print(
    (
        (weather_df["latitude"] < -90) |
        (weather_df["latitude"] > 90)
    ).sum()
)

0

In [16]:
print(
    (
        (weather_df["longitude"] < -180) |
        (weather_df["longitude"] > 180)
    ).sum()
)

0

In [17]:
weather_df["market"].str.strip().eq("").sum()

0

In [18]:
weather_df["market"].str.strip().eq("").sum()

0