In [1]:
import pandas as pd

In [2]:
dataset1 = pd.read_csv("Dataset1_Cleaned_AGMARKNET.csv")

dataset2 = pd.read_csv("Dataset2_Cleaned_Market_Locations.csv")

dataset3 = pd.read_csv("Dataset3_Cleaned_Weather.csv")

In [3]:
print("Dataset 1 :", dataset1.shape)

print("Dataset 2 :", dataset2.shape)

print("Dataset 3 :", dataset3.shape)

Dataset 1 : (9049, 10)
Dataset 2 : (1391, 5)
Dataset 3 : (1391, 8)

In [4]:
dataset1.head()

,state,district,market,commodity,variety,grade,arrival_date,min_price,max_price,modal_price
0,Odisha,Sambalpur,Sahaspur APMC,Little gourd(Kundru),Other,Local,13/07/2026,1600.0,2000.0,1800.0
1,Odisha,Mayurbhanja,Baripada APMC,Ridgeguard(Tori),Ridgeguard(Tori),Local,13/07/2026,4000.0,5000.0,4500.0
2,Keralam,Kozhikode(Calicut),Mukkom Market,Apple,Other,Large,13/07/2026,26000.0,27000.0,26500.0
3,Keralam,Kozhikode(Calicut),Mukkom Market,Bitter gourd,Bitter Gourd,FAQ,13/07/2026,6000.0,6400.0,6200.0
4,Keralam,Kozhikode(Calicut),Mukkom Market,Carrot,Carrot,FAQ,13/07/2026,6000.0,6500.0,6200.0

In [5]:
dataset2.head()

     state            district               market   latitude  longitude
0   Odisha           Sambalpur        Sahaspur APMC  21.341608  83.958399
1   Odisha         Mayurbhanja        Baripada APMC  21.954103  86.742898
2  Keralam  Kozhikode(Calicut)        Mukkom Market  11.248020  75.780400
3  Keralam             Wayanad  Mananthavady Market  11.678470  75.975073
4  Gujarat              Rajkot          Jasdan APMC  22.037500  71.206497

In [6]:
dataset3.head()

,market,latitude,longitude,temperature,humidity,rainfall,wind_speed,weather_code
0,Sahaspur APMC,21.341608,83.958399,30.7,67.0,0.8,17.3,51
1,Baripada APMC,21.954103,86.742898,29.4,85.0,3.6,15.7,55
2,Mukkom Market,11.248020,75.780400,27.1,86.0,2.7,22.9,51
3,Mananthavady Market,11.678470,75.975073,23.2,91.0,3.3,11.5,51
4,Jasdan APMC,22.037500,71.206497,29.0,72.0,0.0,30.9,3

In [7]:
merged_df = dataset1.merge(
    dataset2[
        [
            "state",
            "district",
            "market",
            "latitude",
            "longitude"
        ]
    ],
    on=["state", "district", "market"],
    how="left",
    validate="many_to_one"
)

print(merged_df.shape)

(9049, 12)

In [8]:
print(merged_df[["latitude", "longitude"]].isnull().sum())

latitude     0
longitude    0
dtype: int64

In [9]:
print(dataset3.columns.tolist())

['market', 'latitude', 'longitude', 'temperature', 'humidity', 'rainfall', 'wind_speed', 'weather_code']

In [10]:
print(dataset2.columns.tolist())

['state', 'district', 'market', 'latitude', 'longitude']

In [11]:
final_df = merged_df.merge(

    dataset3[
        [
            "market",
            "latitude",
            "longitude",
            "temperature",
            "humidity",
            "rainfall",
            "wind_speed",
            "weather_code"
        ]
    ],

    on=[
        "market",
        "latitude",
        "longitude"
    ],

    how="left",
    validate="many_to_one"

)

print(final_df.shape)

(9049, 17)

In [12]:
print(final_df.isnull().sum())

state            0
district         0
market           0
commodity        0
variety          0
grade            0
arrival_date     0
min_price        0
max_price        0
modal_price      0
latitude         0
longitude        0
temperature      0
humidity        28
rainfall         0
wind_speed       0
weather_code     0
dtype: int64

In [13]:
print(final_df.duplicated().sum())

0

In [14]:
final_df[final_df["humidity"].isnull()][
    ["state","district","market","latitude","longitude"]
]

,state,district,market,latitude,longitude
219,Tamil Nadu,Dharmapuri,Karimangalam(Uzhavar Sandhai),12.304705,78.208163
220,Tamil Nadu,Dharmapuri,Karimangalam(Uzhavar Sandhai),12.304705,78.208163
221,Tamil Nadu,Dharmapuri,Karimangalam(Uzhavar Sandhai),12.304705,78.208163
222,Tamil Nadu,Dharmapuri,Karimangalam(Uzhavar Sandhai),12.304705,78.208163
223,Tamil Nadu,Dharmapuri,Karimangalam(Uzhavar Sandhai),12.304705,78.208163
2109,Madhya Pradesh,Dhar,Rajgarh APMC,22.677601,74.947502
2110,Madhya Pradesh,Dhar,Rajgarh APMC,22.677601,74.947502
3492,Tamil Nadu,Dharmapuri,Karimangalam(Uzhavar Sandhai),12.304705,78.208163
3493,Tamil Nadu,Dharmapuri,Karimangalam(Uzhavar Sandhai),12.304705,78.208163
3494,Tamil Nadu,Dharmapuri,Karimangalam(Uzhavar Sandhai),12.304705,78.208163
3495,Tamil Nadu,Dharmapuri,Karimangalam(Uzhavar Sandhai),12.304705,78.208163
3496,Tamil Nadu,Dharmapuri,Karimangalam(Uzhavar Sandhai),12.304705,78.208163
3497,Tamil Nadu,Dharmapuri,Karimangalam(Uzhavar Sandhai),12.304705,78.208163
5453,Madhya Pradesh,Dhar,Rajgarh APMC,22.677601,74.947502
5454,Madhya Pradesh,Dhar,Rajgarh APMC,22.677601,74.947502
6250,Tamil Nadu,Coimbatore,Thiruppur APMC,10.793908,77.269322
6794,Tamil Nadu,Dharmapuri,Karimangalam(Uzhavar Sandhai),12.304705,78.208163
6795,Tamil Nadu,Dharmapuri,Karimangalam(Uzhavar Sandhai),12.304705,78.208163
6796,Tamil Nadu,Dharmapuri,Karimangalam(Uzhavar Sandhai),12.304705,78.208163
6797,Tamil Nadu,Dharmapuri,Karimangalam(Uzhavar Sandhai),12.304705,78.208163
6798,Tamil Nadu,Dharmapuri,Karimangalam(Uzhavar Sandhai),12.304705,78.208163
6799,Tamil Nadu,Dharmapuri,Karimangalam(Uzhavar Sandhai),12.304705,78.208163
6800,Tamil Nadu,Dharmapuri,Karimangalam(Uzhavar Sandhai),12.304705,78.208163
6801,Tamil Nadu,Dharmapuri,Karimangalam(Uzhavar Sandhai),12.304705,78.208163
6802,Tamil Nadu,Dharmapuri,Karimangalam(Uzhavar Sandhai),12.304705,78.208163
6803,Tamil Nadu,Dharmapuri,Karimangalam(Uzhavar Sandhai),12.304705,78.208163
6804,Tamil Nadu,Dharmapuri,Karimangalam(Uzhavar Sandhai),12.304705,78.208163
6805,Tamil Nadu,Dharmapuri,Karimangalam(Uzhavar Sandhai),12.304705,78.208163

In [15]:
print("Rows:", final_df.shape[0])
print("Columns:", final_df.shape[1])

assert final_df.shape[0] == 9049, "Row count mismatch!"

assert final_df.duplicated().sum() == 0, "Duplicate rows found!"

assert final_df[
    ["latitude","longitude","temperature"]
].isnull().sum().sum() == 0, "Missing values detected!"

print("✅ Final Dataset Validation Passed")

Rows: 9049
Columns: 17
✅ Final Dataset Validation Passed

In [23]:
final_df.to_csv(
    "Master_Agriculture_Mandi_Dataset.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Master Dataset Saved Successfully!")

Master Dataset Saved Successfully!

In [24]:
dataset4 = pd.read_csv("Master_Agriculture_Mandi_Dataset.csv")

In [25]:
dataset4.shape

(9049, 17)