#### Raw API Data
      ↓
#### Data Cleaning
      ↓
#### Geocoding
      ↓
#### Weather Data
      ↓
#### Data Validation
      ↓
#### Data Merging
      ↓
#### Data Preprocessing
      ↓
#### Processed_Agriculture_Mandi_Dataset.csv

In [75]:
import pandas as pd

In [76]:
import numpy as np

In [77]:
df=pd.read_csv("Master_Agriculture_Mandi_Dataset.csv")

In [78]:
df.shape

(9049, 17)

In [79]:
df.head()

,state,district,market,commodity,variety,grade,arrival_date,min_price,max_price,modal_price,latitude,longitude,temperature,humidity,rainfall,wind_speed,weather_code
0,Odisha,Sambalpur,Sahaspur APMC,Little gourd(Kundru),Other,Local,13/07/2026,1600.0,2000.0,1800.0,21.341608,83.958399,30.7,67.0,0.8,17.3,51
1,Odisha,Mayurbhanja,Baripada APMC,Ridgeguard(Tori),Ridgeguard(Tori),Local,13/07/2026,4000.0,5000.0,4500.0,21.954103,86.742898,29.4,85.0,3.6,15.7,55
2,Keralam,Kozhikode(Calicut),Mukkom Market,Apple,Other,Large,13/07/2026,26000.0,27000.0,26500.0,11.248020,75.780400,27.1,86.0,2.7,22.9,51
3,Keralam,Kozhikode(Calicut),Mukkom Market,Bitter gourd,Bitter Gourd,FAQ,13/07/2026,6000.0,6400.0,6200.0,11.248020,75.780400,27.1,86.0,2.7,22.9,51
4,Keralam,Kozhikode(Calicut),Mukkom Market,Carrot,Carrot,FAQ,13/07/2026,6000.0,6500.0,6200.0,11.248020,75.780400,27.1,86.0,2.7,22.9,51

In [80]:
df.tail()

,state,district,market,commodity,variety,grade,arrival_date,min_price,max_price,modal_price,latitude,longitude,temperature,humidity,rainfall,wind_speed,weather_code
9044,Keralam,Ernakulam,Thrippunithura Market,Onion,Big,Medium,13/07/2026,4000.0,4000.0,4000.0,9.953891,76.329501,28.1,81.0,1.1,20.0,51
9045,Keralam,Ernakulam,Thrippunithura Market,Tomato,Tomato,Medium,13/07/2026,4500.0,5000.0,4700.0,9.953891,76.329501,28.1,81.0,1.1,20.0,51
9046,Odisha,Balasore,Balasore APMC,Brinjal,Round,Grade B,13/07/2026,4500.0,4500.0,4500.0,21.492660,86.933480,29.7,85.0,7.7,14.2,61
9047,Odisha,Balasore,Balasore APMC,Pumpkin,Pumpkin,Grade B,13/07/2026,800.0,800.0,800.0,21.492660,86.933480,29.7,85.0,7.7,14.2,61
9048,Keralam,Kannur,Thalasserry Market,Coconut Oil,Other,FAQ,13/07/2026,23500.0,24500.0,24000.0,11.857085,75.412288,27.5,85.0,5.0,22.2,53

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9049 entries, 0 to 9048
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   state         9049 non-null   object
 1   district      9049 non-null   object
 2   market        9049 non-null   object
 3   commodity     9049 non-null   object
 4   variety       9049 non-null   object
 5   grade         9049 non-null   object
 6   arrival_date  9049 non-null   object
 7   min_price     9049 non-null   float64
 8   max_price     9049 non-null   float64
 9   modal_price   9049 non-null   float64
 10  latitude      9049 non-null   float64
 11  longitude     9049 non-null   float64
 12  temperature   9049 non-null   float64
 13  humidity      9021 non-null   float64
 14  rainfall      9049 non-null   float64
 15  wind_speed    9049 non-null   float64
 16  weather_code  9049 non-null   int64
dtypes: float64(9), int64(1), object(7)
memory usage: 1.2+ MB

In [82]:
df.describe()

,min_price,max_price,modal_price,latitude,longitude,temperature,humidity,rainfall,wind_speed,weather_code
count,9049.000000,9049.000000,9049.000000,9049.000000,9049.000000,9049.000000,9021.000000,9049.000000,9049.000000,9049.000000
mean,4707.925681,5575.456666,5165.367825,17.969625,78.160751,29.638745,66.302849,1.578208,19.559476,24.808045
std,5456.398145,6338.743586,5871.082756,7.593569,3.691239,2.596550,11.705536,7.188085,5.449713,25.045493
min,0.850000,2.000000,1.000000,8.178990,69.448779,16.000000,43.000000,0.000000,3.400000,1.000000
25%,2150.000000,2500.000000,2425.000000,11.107192,76.492088,28.100000,57.000000,0.000000,15.900000,3.000000
50%,3500.000000,4000.000000,3750.000000,13.610720,77.813907,30.000000,66.000000,0.000000,20.200000,3.000000
75%,5500.000000,6500.000000,6000.000000,24.243299,79.131563,31.800000,76.000000,0.400000,23.300000,51.000000
max,129500.000000,140000.000000,129512.560000,34.217201,94.814876,34.800000,99.000000,169.900000,36.700000,65.000000

In [83]:
df.dtypes

state            object
district         object
market           object
commodity        object
variety          object
grade            object
arrival_date     object
min_price       float64
max_price       float64
modal_price     float64
latitude        float64
longitude       float64
temperature     float64
humidity        float64
rainfall        float64
wind_speed      float64
weather_code      int64
dtype: object

In [84]:
df.columns

Index(['state', 'district', 'market', 'commodity', 'variety', 'grade',
       'arrival_date', 'min_price', 'max_price', 'modal_price', 'latitude',
       'longitude', 'temperature', 'humidity', 'rainfall', 'wind_speed',
       'weather_code'],
      dtype='object')

In [85]:
sorted(df["state"].unique())

['Andaman and Nicobar',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chattisgarh',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu and Kashmir',
 'Karnataka',
 'Keralam',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'NCT of Delhi',
 'Nagaland',
 'Odisha',
 'Pondicherry',
 'Punjab',
 'Rajasthan',
 'Tamil Nadu',
 'Telangana',
 'Tripura',
 'Uttar Pradesh',
 'Uttarakhand',
 'West Bengal']

In [86]:
# Display column names

df.columns

Index(['state', 'district', 'market', 'commodity', 'variety', 'grade',
       'arrival_date', 'min_price', 'max_price', 'modal_price', 'latitude',
       'longitude', 'temperature', 'humidity', 'rainfall', 'wind_speed',
       'weather_code'],
      dtype='object')

In [87]:
# Convert arrival_date to datetime

df["arrival_date"] = pd.to_datetime(df["arrival_date"])

C:\Users\arund\AppData\Local\Temp\ipykernel_16124\956522110.py:3: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["arrival_date"] = pd.to_datetime(df["arrival_date"])

In [88]:
df.dtypes

state                   object
district                object
market                  object
commodity               object
variety                 object
grade                   object
arrival_date    datetime64[ns]
min_price              float64
max_price              float64
modal_price            float64
latitude               float64
longitude              float64
temperature            float64
humidity               float64
rainfall               float64
wind_speed             float64
weather_code             int64
dtype: object

In [89]:
df.head()

,state,district,market,commodity,variety,grade,arrival_date,min_price,max_price,modal_price,latitude,longitude,temperature,humidity,rainfall,wind_speed,weather_code
0,Odisha,Sambalpur,Sahaspur APMC,Little gourd(Kundru),Other,Local,2026-07-13,1600.0,2000.0,1800.0,21.341608,83.958399,30.7,67.0,0.8,17.3,51
1,Odisha,Mayurbhanja,Baripada APMC,Ridgeguard(Tori),Ridgeguard(Tori),Local,2026-07-13,4000.0,5000.0,4500.0,21.954103,86.742898,29.4,85.0,3.6,15.7,55
2,Keralam,Kozhikode(Calicut),Mukkom Market,Apple,Other,Large,2026-07-13,26000.0,27000.0,26500.0,11.248020,75.780400,27.1,86.0,2.7,22.9,51
3,Keralam,Kozhikode(Calicut),Mukkom Market,Bitter gourd,Bitter Gourd,FAQ,2026-07-13,6000.0,6400.0,6200.0,11.248020,75.780400,27.1,86.0,2.7,22.9,51
4,Keralam,Kozhikode(Calicut),Mukkom Market,Carrot,Carrot,FAQ,2026-07-13,6000.0,6500.0,6200.0,11.248020,75.780400,27.1,86.0,2.7,22.9,51

In [90]:
df.isnull().sum()

state            0
district         0
market           0
commodity        0
variety          0
grade            0
arrival_date     0
min_price        0
max_price        0
modal_price      0
latitude         0
longitude        0
temperature      0
humidity        28
rainfall         0
wind_speed       0
weather_code     0
dtype: int64

In [91]:
# Calculate missing value percentage

missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage.round(2)

state           0.00
district        0.00
market          0.00
commodity       0.00
variety         0.00
grade           0.00
arrival_date    0.00
min_price       0.00
max_price       0.00
modal_price     0.00
latitude        0.00
longitude       0.00
temperature     0.00
humidity        0.31
rainfall        0.00
wind_speed      0.00
weather_code    0.00
dtype: float64

In [92]:
df["humidity"].isnull().sum()

28

In [93]:
median_humidity= df["humidity"].median()

In [94]:
df["humidity"]= df["humidity"].fillna(median_humidity)

In [95]:
df.isnull().sum()

state           0
district        0
market          0
commodity       0
variety         0
grade           0
arrival_date    0
min_price       0
max_price       0
modal_price     0
latitude        0
longitude       0
temperature     0
humidity        0
rainfall        0
wind_speed      0
weather_code    0
dtype: int64

In [96]:
duplicate_rows=df.duplicated().sum()

print("Duplicate Rows:", duplicate_rows)

Duplicate Rows: 0

In [97]:
df.shape

(9049, 17)

In [98]:
# Validate price relationship

invalid_prices = df[(df["min_price"] > df["modal_price"]) |(df["modal_price"] > df["max_price"])]

invalid_prices

Empty DataFrame
Columns: [state, district, market, commodity, variety, grade, arrival_date, min_price, max_price, modal_price, latitude, longitude, temperature, humidity, rainfall, wind_speed, weather_code]
Index: []

In [99]:
print("Invalid Price Records:", len(invalid_prices))

Invalid Price Records: 0

In [100]:
df.shape

(9049, 17)

In [101]:
# Check invalid longitude values

invalid_longitude = df[
    (df["longitude"] < -180) |
    (df["longitude"] > 180)
]

invalid_longitude

Empty DataFrame
Columns: [state, district, market, commodity, variety, grade, arrival_date, min_price, max_price, modal_price, latitude, longitude, temperature, humidity, rainfall, wind_speed, weather_code]
Index: []

In [102]:
# Check invalid temperature values

invalid_temperature = df[
    (df["temperature"] < -20) |
    (df["temperature"] > 60)
]

invalid_temperature

Empty DataFrame
Columns: [state, district, market, commodity, variety, grade, arrival_date, min_price, max_price, modal_price, latitude, longitude, temperature, humidity, rainfall, wind_speed, weather_code]
Index: []

In [103]:
# Check invalid humidity values

invalid_humidity = df[
    (df["humidity"] < 0) |
    (df["humidity"] > 100)
]

invalid_humidity

Empty DataFrame
Columns: [state, district, market, commodity, variety, grade, arrival_date, min_price, max_price, modal_price, latitude, longitude, temperature, humidity, rainfall, wind_speed, weather_code]
Index: []

In [104]:
# Check invalid rainfall values

invalid_rainfall = df[
    df["rainfall"] < 0
]

invalid_rainfall

Empty DataFrame
Columns: [state, district, market, commodity, variety, grade, arrival_date, min_price, max_price, modal_price, latitude, longitude, temperature, humidity, rainfall, wind_speed, weather_code]
Index: []

In [105]:
# Check invalid wind speed values

invalid_wind = df[
    df["wind_speed"] < 0
]

invalid_wind

Empty DataFrame
Columns: [state, district, market, commodity, variety, grade, arrival_date, min_price, max_price, modal_price, latitude, longitude, temperature, humidity, rainfall, wind_speed, weather_code]
Index: []

In [106]:
# Check final dataset shape

print(df.shape)

(9049, 17)

In [107]:
# Save processed dataset

df.to_csv("Processed_Agriculture_Mandi_Dataset.csv",index=False)
print("Processed dataset saved successfully.")

Processed dataset saved successfully.

In [108]:
import pandas as pd

In [109]:
import numpy as np

In [110]:
df1=pd.read_csv("Processed_Agriculture_Mandi_Dataset.csv")

## 07 Feature Engineering And EDA

In [111]:
df1.shape

(9049, 17)

In [112]:
# 1. Create Price Spread
df1["price_spread"] = df1["max_price"] - df1["min_price"]

In [113]:
# Preview
df1[["min_price", "max_price", "price_spread"]].head()

   min_price  max_price  price_spread
0     1600.0     2000.0         400.0
1     4000.0     5000.0        1000.0
2    26000.0    27000.0        1000.0
3     6000.0     6400.0         400.0
4     6000.0     6500.0         500.0

In [114]:
# 2. Create Average Price
df1["average_price"] = (df1["min_price"] + df1["max_price"]) / 2

In [115]:
# Preview
df1[["min_price", "max_price", "average_price"]].head()

   min_price  max_price  average_price
0     1600.0     2000.0         1800.0
1     4000.0     5000.0         4500.0
2    26000.0    27000.0        26500.0
3     6000.0     6400.0         6200.0
4     6000.0     6500.0         6250.0

In [116]:
# 3. Create Price Category

def price_category(price):
    if price < 2000:
        return "Low"
    elif price <= 5000:
        return "Medium"
    else:
        return "High"

df1["price_category"] = df1["average_price"].apply(price_category)

In [117]:
# Preview
df1[["average_price", "price_category"]].head()

   average_price price_category
0         1800.0            Low
1         4500.0         Medium
2        26500.0           High
3         6200.0           High
4         6250.0           High

In [118]:
# 4. Create Temperature Category

def temperature_category(temp):
    if temp < 20:
        return "Cold"
    elif temp <= 30:
        return "Moderate"
    else:
        return "Hot"

df1["temperature_category"] = df1["temperature"].apply(temperature_category)

In [119]:
# Preview
df1[["temperature", "temperature_category"]].head()

   temperature temperature_category
0         30.7                  Hot
1         29.4             Moderate
2         27.1             Moderate
3         27.1             Moderate
4         27.1             Moderate

In [120]:
# 5. Create Humidity Category

def humidity_category(humidity):
    if humidity < 40:
        return "Low"
    elif humidity <= 70:
        return "Medium"
    else:
        return "High"

df1["humidity_category"] = df["humidity"].apply(humidity_category)

In [121]:
# Preview
df1[["humidity", "humidity_category"]].head()

   humidity humidity_category
0      67.0            Medium
1      85.0              High
2      86.0              High
3      86.0              High
4      86.0              High

In [122]:
# 6. Create Rainfall Category

def rainfall_category(rainfall):
    if rainfall == 0:
        return "No Rain"
    elif rainfall <= 20:
        return "Light Rain"
    else:
        return "Heavy Rain"

df1["rainfall_category"] = df["rainfall"].apply(rainfall_category)

In [123]:
# Preview
df1[["rainfall", "rainfall_category"]].head()

   rainfall rainfall_category
0       0.8        Light Rain
1       3.6        Light Rain
2       2.7        Light Rain
3       2.7        Light Rain
4       2.7        Light Rain

In [124]:
# Display newly created feature columns

new_features = [
    "price_spread",
    "average_price",
    "price_category",
    "temperature_category",
    "humidity_category",
    "rainfall_category"
]

df1[new_features].head()

,price_spread,average_price,price_category,temperature_category,humidity_category,rainfall_category
0,400.0,1800.0,Low,Hot,Medium,Light Rain
1,1000.0,4500.0,Medium,Moderate,High,Light Rain
2,1000.0,26500.0,High,Moderate,High,Light Rain
3,400.0,6200.0,High,Moderate,High,Light Rain
4,500.0,6250.0,High,Moderate,High,Light Rain

In [125]:
df1.head()

,state,district,market,commodity,variety,grade,arrival_date,min_price,max_price,modal_price,...,humidity,rainfall,wind_speed,weather_code,price_spread,average_price,price_category,temperature_category,humidity_category,rainfall_category
0,Odisha,Sambalpur,Sahaspur APMC,Little gourd(Kundru),Other,Local,2026-07-13,1600.0,2000.0,1800.0,...,67.0,0.8,17.3,51,400.0,1800.0,Low,Hot,Medium,Light Rain
1,Odisha,Mayurbhanja,Baripada APMC,Ridgeguard(Tori),Ridgeguard(Tori),Local,2026-07-13,4000.0,5000.0,4500.0,...,85.0,3.6,15.7,55,1000.0,4500.0,Medium,Moderate,High,Light Rain
2,Keralam,Kozhikode(Calicut),Mukkom Market,Apple,Other,Large,2026-07-13,26000.0,27000.0,26500.0,...,86.0,2.7,22.9,51,1000.0,26500.0,High,Moderate,High,Light Rain
3,Keralam,Kozhikode(Calicut),Mukkom Market,Bitter gourd,Bitter Gourd,FAQ,2026-07-13,6000.0,6400.0,6200.0,...,86.0,2.7,22.9,51,400.0,6200.0,High,Moderate,High,Light Rain
4,Keralam,Kozhikode(Calicut),Mukkom Market,Carrot,Carrot,FAQ,2026-07-13,6000.0,6500.0,6200.0,...,86.0,2.7,22.9,51,500.0,6250.0,High,Moderate,High,Light Rain

In [127]:
df1.shape

(9049, 23)

In [128]:
# Save the final feature engineered dataset
df1.to_csv("Final_Agriculture_Mandi_Dataset.csv", index=False)

print("Final dataset saved successfully.")

Final dataset saved successfully.